[package]
name = "tracing-tree"
version = "0.1.5"
authors = ["David Barsky <me@davidbarsky.com>", "Nathan Whitaker"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "A Tracing Layer which prints a tree of spans and events."
repository = "https://github.com/davidbarsky/tracing-tree"
readme = "README.md"

[dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.2", default-features = false, features = ["registry", "fmt"] }
termcolor = "1.0.5"
ansi_term = "0.12.1"
chrono = "0.4.10"
atty = "0.2.14"
